"""Plugin catalog for StrategyRuntime research cartridges.

Catalog presence is not runtime promotion. Runtime activation still requires
Config.STRATEGY_RUNTIME_ENABLED plus an explicit Config.ENABLED_STRATEGIES list.
"""

from __future__ import annotations

import copy
from collections.abc import Iterable
from typing import Any


STRATEGY_CATALOG: dict[str, dict[str, Any]] = {
    "fixture_long": {
        "enabled": False,
        "module": "trader.strategies.plugins.fixture",
        "class": "FixtureLongStrategy",
        "params": {},
    },
    "fixture_exit": {
        "enabled": False,
        "module": "trader.strategies.plugins.fixture",
        "class": "FixtureExitStrategy",
        "params": {},
    },
    "macd_zero_line_btc_1d": {
        "enabled": False,
        "module": "trader.strategies.plugins.macd_zero_line",
        "class": "MacdZeroLineLongStrategy",
        "params": {"symbol": "BTC/USDT", "timeframe": "1d"},
    },
    "macd_zero_line_btc_1d_trending_up": {
        "enabled": False,
        "module": "trader.strategies.plugins.macd_zero_line_trending_up",
        "class": "MacdZeroLineTrendingUpStrategy",
        "params": {
            "symbol": "BTC/USDT",
            "timeframe": "1d",
            "stop_atr_mult": 1.5,
            "require_signal_confirmation": True,
            "emit_once": True,
            "trend_spread_min": 0.005,
        },
    },
    "macd_signal_btc_4h_trending_up": {
        "enabled": False,
        "module": "trader.strategies.plugins.macd_signal_trending_up_4h",
        "class": "MacdSignalTrendingUp4hStrategy",
        "params": {
            "symbol": "BTC/USDT",
            "entry_timeframe": "4h",
            "trend_timeframe": "1d",
            "stop_atr_mult": 1.5,
            "require_signal_confirmation": True,
            "emit_once": True,
            "trend_spread_min": 0.005,
        },
    },
    "macd_signal_btc_4h_trending_up_confirmed": {
        "enabled": False,
        "module": "trader.strategies.plugins.macd_signal_trending_up_4h_confirmed",
        "class": "MacdSignalTrendingUp4hConfirmedStrategy",
        "params": {
            "symbol": "BTC/USDT",
            "entry_timeframe": "4h",
            "trend_timeframe": "1d",
            "stop_atr_mult": 1.5,
            "emit_once": True,
            "trend_spread_min": 0.005,
        },
    },
    "macd_signal_btc_4h_trending_up_confirmed_failfast": {
        "enabled": False,
        "module": "trader.strategies.plugins.macd_signal_trending_up_4h_confirmed_failfast",
        "class": "MacdSignalTrendingUp4hConfirmedFailFastStrategy",
        "params": {
            "symbol": "BTC/USDT",
            "entry_timeframe": "4h",
            "trend_timeframe": "1d",
            "stop_atr_mult": 1.5,
            "emit_once": True,
            "trend_spread_min": 0.005,
            "failed_continuation_bars": 2,
        },
    },
    "macd_signal_btc_4h_trending_up_underwater_ema_exit": {
        "enabled": False,
        "module": "trader.strategies.plugins.macd_signal_trending_up_4h_underwater_ema_exit",
        "class": "MacdSignalTrendingUp4hUnderwaterEmaExitStrategy",
        "params": {
            "symbol": "BTC/USDT",
            "entry_timeframe": "4h",
            "trend_timeframe": "1d",
            "stop_atr_mult": 1.5,
            "require_signal_confirmation": True,
            "emit_once": True,
            "trend_spread_min": 0.005,
            "underwater_ema_exit_bars": 1,
        },
    },
    "macd_signal_btc_4h_trending_up_staged_derisk_giveback": {
        "enabled": False,
        "module": "trader.strategies.plugins.macd_signal_trending_up_4h_staged_derisk_giveback",
        "class": "MacdSignalTrendingUp4hStagedDeriskGivebackStrategy",
        "params": {
            "symbol": "BTC/USDT",
            "entry_timeframe": "4h",
            "trend_timeframe": "1d",
            "stop_atr_mult": 1.5,
            "require_signal_confirmation": True,
            "emit_once": True,
            "trend_spread_min": 0.005,
            "derisk_arm_r": 1.0,
            "derisk_giveback_r": 0.75,
            "derisk_close_pct": 0.5,
            "giveback_exit_arm_r": 1.5,
            "giveback_exit_floor_r": 0.25,
        },
    },
    "macd_signal_btc_4h_trending_up_staged_derisk_giveback_partial67": {
        "enabled": False,
        "module": "trader.strategies.plugins.macd_signal_trending_up_4h_staged_derisk_giveback_partial67",
        "class": "MacdSignalTrendingUp4hStagedDeriskGivebackPartial67Strategy",
        "params": {
            "symbol": "BTC/USDT",
            "entry_timeframe": "4h",
            "trend_timeframe": "1d",
            "stop_atr_mult": 1.5,
            "require_signal_confirmation": True,
            "emit_once": True,
            "trend_spread_min": 0.005,
            "derisk_arm_r": 1.0,
            "derisk_giveback_r": 0.75,
            "derisk_close_pct": 0.67,
            "giveback_exit_arm_r": 1.5,
            "giveback_exit_floor_r": 0.25,
        },
    },
    "macd_signal_btc_4h_trending_up_staged_derisk_giveback_partial67_late_entry_filter": {
        "enabled": False,
        "module": "trader.strategies.plugins.macd_signal_trending_up_4h_staged_derisk_giveback_partial67_late_entry_filter",
        "class": "MacdSignalTrendingUp4hStagedDeriskGivebackPartial67LateEntryFilterStrategy",
        "params": {
            "symbol": "BTC/USDT",
            "entry_timeframe": "4h",
            "trend_timeframe": "1d",
            "stop_atr_mult": 1.5,
            "require_signal_confirmation": True,
            "emit_once": True,
            "trend_spread_min": 0.005,
            "derisk_arm_r": 1.0,
            "derisk_giveback_r": 0.75,
            "derisk_close_pct": 0.67,
            "giveback_exit_arm_r": 1.5,
            "giveback_exit_floor_r": 0.25,
            "entry_ema_extension_atr_max": 1.25,
        },
    },
    "macd_signal_btc_4h_trending_up_staged_derisk_giveback_partial67_context_gated_late_entry_filter": {
        "enabled": False,
        "module": "trader.strategies.plugins.macd_signal_trending_up_4h_staged_derisk_giveback_partial67_context_gated_late_entry_filter",
        "class": "MacdSignalTrendingUp4hStagedDeriskGivebackPartial67ContextGatedLateEntryFilterStrategy",
        "params": {
            "symbol": "BTC/USDT",
            "entry_timeframe": "4h",
            "trend_timeframe": "1d",
            "stop_atr_mult": 1.5,
            "require_signal_confirmation": True,
            "emit_once": True,
            "trend_spread_min": 0.005,
            "derisk_arm_r": 1.0,
            "derisk_giveback_r": 0.75,
            "derisk_close_pct": 0.67,
            "giveback_exit_arm_r": 1.5,
            "giveback_exit_floor_r": 0.25,
            "entry_ema_extension_atr_max": 1.25,
            "trend_spread_slope_bars": 3,
            "weak_tape_trend_spread_delta_max": 0.0,
            "entry_bbw_ratio_min": 0.75,
        },
    },
    "macd_signal_btc_4h_trending_up_staged_derisk_giveback_partial67_chop_filter": {
        "enabled": False,
        "module": "trader.strategies.plugins.macd_signal_trending_up_4h_staged_derisk_giveback_partial67_chop_filter",
        "class": "MacdSignalTrendingUp4hStagedDeriskGivebackPartial67ChopFilterStrategy",
        "params": {
            "symbol": "BTC/USDT",
            "entry_timeframe": "4h",
            "trend_timeframe": "1d",
            "stop_atr_mult": 1.5,
            "require_signal_confirmation": True,
            "emit_once": True,
            "trend_spread_min": 0.005,
            "derisk_arm_r": 1.0,
            "derisk_giveback_r": 0.75,
            "derisk_close_pct": 0.67,
            "giveback_exit_arm_r": 1.5,
            "giveback_exit_floor_r": 0.25,
            "entry_adx_min": 22.0,
        },
    },
    "macd_signal_btc_4h_trending_up_staged_derisk_giveback_partial67_local_spread_filter": {
        "enabled": False,
        "module": "trader.strategies.plugins.macd_signal_trending_up_4h_staged_derisk_giveback_partial67_local_spread_filter",
        "class": "MacdSignalTrendingUp4hStagedDeriskGivebackPartial67LocalSpreadFilterStrategy",
        "params": {
            "symbol": "BTC/USDT",
            "entry_timeframe": "4h",
            "trend_timeframe": "1d",
            "stop_atr_mult": 1.5,
            "require_signal_confirmation": True,
            "emit_once": True,
            "trend_spread_min": 0.005,
            "derisk_arm_r": 1.0,
            "derisk_giveback_r": 0.75,
            "derisk_close_pct": 0.67,
            "giveback_exit_arm_r": 1.5,
            "giveback_exit_floor_r": 0.25,
            "entry_local_spread_min": 0.002,
        },
    },
    "macd_signal_btc_4h_trending_up_staged_derisk_giveback_partial67_chop_trend_filter": {
        "enabled": False,
        "module": "trader.strategies.plugins.macd_signal_trending_up_4h_staged_derisk_giveback_partial67_chop_trend_filter",
        "class": "MacdSignalTrendingUp4hStagedDeriskGivebackPartial67ChopTrendFilterStrategy",
        "params": {
            "symbol": "BTC/USDT",
            "entry_timeframe": "4h",
            "trend_timeframe": "1d",
            "stop_atr_mult": 1.5,
            "require_signal_confirmation": True,
            "emit_once": True,
            "trend_spread_min": 0.005,
            "derisk_arm_r": 1.0,
            "derisk_giveback_r": 0.75,
            "derisk_close_pct": 0.67,
            "giveback_exit_arm_r": 1.5,
            "giveback_exit_floor_r": 0.25,
            "entry_bbw_ratio_min": 0.75,
        },
    },
    "macd_signal_btc_4h_trending_up_staged_derisk_giveback_partial67_remainder_ratchet": {
        "enabled": False,
        "module": "trader.strategies.plugins.macd_signal_trending_up_4h_staged_derisk_giveback_partial67_remainder_ratchet",
        "class": "MacdSignalTrendingUp4hStagedDeriskGivebackPartial67RemainderRatchetStrategy",
        "params": {
            "symbol": "BTC/USDT",
            "entry_timeframe": "4h",
            "trend_timeframe": "1d",
            "stop_atr_mult": 1.5,
            "require_signal_confirmation": True,
            "emit_once": True,
            "trend_spread_min": 0.005,
            "derisk_arm_r": 1.0,
            "derisk_giveback_r": 0.75,
            "derisk_close_pct": 0.67,
            "giveback_exit_arm_r": 1.5,
            "giveback_exit_floor_r": 0.25,
            "remainder_ratchet_arm_r": 1.0,
            "remainder_ratchet_giveback_r": 1.0,
        },
    },
    "macd_signal_btc_4h_trending_up_staged_derisk_giveback_partial67_transition_buffer": {
        "enabled": False,
        "module": "trader.strategies.plugins.macd_signal_trending_up_4h_staged_derisk_giveback_partial67_transition_buffer",
        "class": "MacdSignalTrendingUp4hStagedDeriskGivebackPartial67TransitionBufferStrategy",
        "params": {
            "symbol": "BTC/USDT",
            "entry_timeframe": "4h",
            "trend_timeframe": "1d",
            "stop_atr_mult": 1.5,
            "require_signal_confirmation": True,
            "emit_once": True,
            "trend_spread_min": 0.005,
            "derisk_arm_r": 1.0,
            "derisk_giveback_r": 0.75,
            "derisk_close_pct": 0.67,
            "giveback_exit_arm_r": 1.5,
            "giveback_exit_floor_r": 0.25,
            "trend_persistence_bars": 3,
        },
    },
    "macd_signal_btc_4h_trending_up_staged_derisk_giveback_partial67_transition_decay_filter": {
        "enabled": False,
        "module": "trader.strategies.plugins.macd_signal_trending_up_4h_staged_derisk_giveback_partial67_transition_decay_filter",
        "class": "MacdSignalTrendingUp4hStagedDeriskGivebackPartial67TransitionDecayFilterStrategy",
        "params": {
            "symbol": "BTC/USDT",
            "entry_timeframe": "4h",
            "trend_timeframe": "1d",
            "stop_atr_mult": 1.5,
            "require_signal_confirmation": True,
            "emit_once": True,
            "trend_spread_min": 0.005,
            "derisk_arm_r": 1.0,
            "derisk_giveback_r": 0.75,
            "derisk_close_pct": 0.67,
            "giveback_exit_arm_r": 1.5,
            "giveback_exit_floor_r": 0.25,
            "trend_spread_slope_bars": 3,
            "trend_spread_slope_min": 0.0,
        },
    },
    "ema_cross_7_19_long_only": {
        "enabled": False,
        "module": "trader.strategies.plugins.ema_cross_7_19",
        "class": "EmaCross719LongOnlyStrategy",
        "params": {"timeframe": "4h", "atr_mult": 1.5},
    },
    "rsi_mean_reversion_15m": {
        "enabled": False,
        "module": "trader.strategies.plugins.rsi_mean_reversion",
        "class": "RsiMeanReversionStrategy",
        "params": {
            "timeframe": "15m",
            "rsi_entry": 25.0,
            "rsi_exit": 60.0,
            "adx_max": 25.0,
            "adx_exit": 30.0,
            "stop_atr_mult": 1.5,
            "cooldown_bars": 5,
        },
    },
    "rsi_mean_reversion_1h": {
        "enabled": False,
        "module": "trader.strategies.plugins.rsi_mean_reversion_1h",
        "class": "RsiMeanReversion1hStrategy",
        "params": {
            "timeframe": "1h",
            "rsi_entry": 25.0,
            "rsi_exit": 60.0,
            "adx_max": 25.0,
            "adx_exit": 30.0,
            "stop_atr_mult": 1.5,
            "cooldown_bars": 5,
        },
    },
}


def get_strategy_catalog(enabled: Iterable[str] | None = None) -> dict[str, dict[str, Any]]:
    """Return a per-call catalog copy with selected plugin ids enabled."""
    catalog = copy.deepcopy(STRATEGY_CATALOG)
    for strategy_id in enabled or []:
        entry = catalog.get(str(strategy_id))
        if entry is not None:
            entry["enabled"] = True
    return catalog
