"""Plugin catalog for StrategyRuntime research cartridges.

Catalog presence is not runtime promotion. Runtime activation still requires
Config.STRATEGY_RUNTIME_ENABLED plus an explicit Config.ENABLED_STRATEGIES list.
"""

from __future__ import annotations

import copy
from collections.abc import Iterable
from typing import Any


CATALOG_CLASS_RUNTIME = "runtime"
CATALOG_CLASS_FIXTURE = "fixture"
CATALOG_CLASS_ACTIVE_RESEARCH = "active_research"
CATALOG_CLASS_SUPERSEDED_RESEARCH = "superseded_research"
CATALOG_CLASS_RETIRE_CANDIDATE = "retire_candidate"

VALID_CATALOG_CLASSIFICATIONS = frozenset(
    {
        CATALOG_CLASS_RUNTIME,
        CATALOG_CLASS_FIXTURE,
        CATALOG_CLASS_ACTIVE_RESEARCH,
        CATALOG_CLASS_SUPERSEDED_RESEARCH,
        CATALOG_CLASS_RETIRE_CANDIDATE,
    }
)


STRATEGY_CATALOG: dict[str, dict[str, Any]] = {
    "fixture_long": {
        "enabled": False,
        "module": "trader.strategies.plugins.fixture",
        "class": "FixtureLongStrategy",
        "params": {},
    },
    "fixture_exit": {
        "enabled": False,
        "module": "trader.strategies.plugins.fixture",
        "class": "FixtureExitStrategy",
        "params": {},
    },
    "macd_zero_line_btc_1d": {
        "enabled": False,
        "module": "trader.strategies.plugins.macd_zero_line",
        "class": "MacdZeroLineLongStrategy",
        "params": {"symbol": "BTC/USDT", "timeframe": "1d"},
    },
    "macd_zero_line_btc_1d_trending_up": {
        "enabled": False,
        "module": "trader.strategies.plugins.macd_zero_line_trending_up",
        "class": "MacdZeroLineTrendingUpStrategy",
        "params": {
            "symbol": "BTC/USDT",
            "timeframe": "1d",
            "stop_atr_mult": 1.5,
            "require_signal_confirmation": True,
            "emit_once": True,
            "trend_spread_min": 0.005,
        },
    },
    "macd_signal_btc_4h_trending_up": {
        "enabled": False,
        "module": "trader.strategies.plugins.macd_signal_trending_up_4h",
        "class": "MacdSignalTrendingUp4hStrategy",
        "params": {
            "symbol": "BTC/USDT",
            "entry_timeframe": "4h",
            "trend_timeframe": "1d",
            "stop_atr_mult": 1.5,
            "require_signal_confirmation": True,
            "emit_once": True,
            "trend_spread_min": 0.005,
        },
    },
    "macd_signal_btc_4h_trending_up_confirmed": {
        "enabled": False,
        "module": "trader.strategies.plugins.macd_signal_trending_up_4h_confirmed",
        "class": "MacdSignalTrendingUp4hConfirmedStrategy",
        "params": {
            "symbol": "BTC/USDT",
            "entry_timeframe": "4h",
            "trend_timeframe": "1d",
            "stop_atr_mult": 1.5,
            "emit_once": True,
            "trend_spread_min": 0.005,
        },
    },
    "macd_signal_btc_4h_trending_up_confirmed_failfast": {
        "enabled": False,
        "module": "trader.strategies.plugins.macd_signal_trending_up_4h_confirmed_failfast",
        "class": "MacdSignalTrendingUp4hConfirmedFailFastStrategy",
        "params": {
            "symbol": "BTC/USDT",
            "entry_timeframe": "4h",
            "trend_timeframe": "1d",
            "stop_atr_mult": 1.5,
            "emit_once": True,
            "trend_spread_min": 0.005,
            "failed_continuation_bars": 2,
        },
    },
    "macd_signal_btc_4h_trending_up_underwater_ema_exit": {
        "enabled": False,
        "module": "trader.strategies.plugins.macd_signal_trending_up_4h_underwater_ema_exit",
        "class": "MacdSignalTrendingUp4hUnderwaterEmaExitStrategy",
        "params": {
            "symbol": "BTC/USDT",
            "entry_timeframe": "4h",
            "trend_timeframe": "1d",
            "stop_atr_mult": 1.5,
            "require_signal_confirmation": True,
            "emit_once": True,
            "trend_spread_min": 0.005,
            "underwater_ema_exit_bars": 1,
        },
    },
    "macd_signal_btc_4h_trending_up_staged_derisk_giveback": {
        "enabled": False,
        "module": "trader.strategies.plugins.macd_signal_trending_up_4h_staged_derisk_giveback",
        "class": "MacdSignalTrendingUp4hStagedDeriskGivebackStrategy",
        "params": {
            "symbol": "BTC/USDT",
            "entry_timeframe": "4h",
            "trend_timeframe": "1d",
            "stop_atr_mult": 1.5,
            "require_signal_confirmation": True,
            "emit_once": True,
            "trend_spread_min": 0.005,
            "derisk_arm_r": 1.0,
            "derisk_giveback_r": 0.75,
            "derisk_close_pct": 0.5,
            "giveback_exit_arm_r": 1.5,
            "giveback_exit_floor_r": 0.25,
        },
    },
    "macd_signal_btc_4h_trending_up_staged_derisk_giveback_partial67": {
        "enabled": False,
        "module": "trader.strategies.plugins.macd_signal_trending_up_4h_staged_derisk_giveback_partial67",
        "class": "MacdSignalTrendingUp4hStagedDeriskGivebackPartial67Strategy",
        "params": {
            "symbol": "BTC/USDT",
            "entry_timeframe": "4h",
            "trend_timeframe": "1d",
            "stop_atr_mult": 1.5,
            "require_signal_confirmation": True,
            "emit_once": True,
            "trend_spread_min": 0.005,
            "derisk_arm_r": 1.0,
            "derisk_giveback_r": 0.75,
            "derisk_close_pct": 0.67,
            "giveback_exit_arm_r": 1.5,
            "giveback_exit_floor_r": 0.25,
        },
    },
    "macd_signal_btc_4h_trending_up_staged_derisk_giveback_partial67_late_entry_filter": {
        "enabled": False,
        "module": "trader.strategies.plugins.macd_signal_trending_up_4h_staged_derisk_giveback_partial67_late_entry_filter",
        "class": "MacdSignalTrendingUp4hStagedDeriskGivebackPartial67LateEntryFilterStrategy",
        "params": {
            "symbol": "BTC/USDT",
            "entry_timeframe": "4h",
            "trend_timeframe": "1d",
            "stop_atr_mult": 1.5,
            "require_signal_confirmation": True,
            "emit_once": True,
            "trend_spread_min": 0.005,
            "derisk_arm_r": 1.0,
            "derisk_giveback_r": 0.75,
            "derisk_close_pct": 0.67,
            "giveback_exit_arm_r": 1.5,
            "giveback_exit_floor_r": 0.25,
            "entry_ema_extension_atr_max": 1.25,
        },
    },
    "macd_signal_btc_4h_trending_up_staged_derisk_giveback_partial67_context_gated_late_entry_filter": {
        "enabled": False,
        "module": "trader.strategies.plugins.macd_signal_trending_up_4h_staged_derisk_giveback_partial67_context_gated_late_entry_filter",
        "class": "MacdSignalTrendingUp4hStagedDeriskGivebackPartial67ContextGatedLateEntryFilterStrategy",
        "params": {
            "symbol": "BTC/USDT",
            "entry_timeframe": "4h",
            "trend_timeframe": "1d",
            "stop_atr_mult": 1.5,
            "require_signal_confirmation": True,
            "emit_once": True,
            "trend_spread_min": 0.005,
            "derisk_arm_r": 1.0,
            "derisk_giveback_r": 0.75,
            "derisk_close_pct": 0.67,
            "giveback_exit_arm_r": 1.5,
            "giveback_exit_floor_r": 0.25,
            "entry_ema_extension_atr_max": 1.25,
            "trend_spread_slope_bars": 3,
            "weak_tape_trend_spread_delta_max": 0.0,
            "entry_bbw_ratio_min": 0.75,
        },
    },
    "macd_signal_btc_4h_trending_up_staged_derisk_giveback_partial67_trend_decay_only_late_entry_filter": {
        "enabled": False,
        "module": "trader.strategies.plugins.macd_signal_trending_up_4h_staged_derisk_giveback_partial67_trend_decay_only_late_entry_filter",
        "class": "MacdSignalTrendingUp4hStagedDeriskGivebackPartial67TrendDecayOnlyLateEntryFilterStrategy",
        "params": {
            "symbol": "BTC/USDT",
            "entry_timeframe": "4h",
            "trend_timeframe": "1d",
            "stop_atr_mult": 1.5,
            "require_signal_confirmation": True,
            "emit_once": True,
            "trend_spread_min": 0.005,
            "derisk_arm_r": 1.0,
            "derisk_giveback_r": 0.75,
            "derisk_close_pct": 0.67,
            "giveback_exit_arm_r": 1.5,
            "giveback_exit_floor_r": 0.25,
            "entry_ema_extension_atr_max": 1.25,
            "trend_spread_slope_bars": 3,
            "weak_tape_trend_spread_delta_max": 0.0,
        },
    },
    "macd_signal_btc_4h_trending_up_staged_derisk_giveback_partial67_chop_trend_only_late_entry_filter": {
        "enabled": False,
        "module": "trader.strategies.plugins.macd_signal_trending_up_4h_staged_derisk_giveback_partial67_chop_trend_only_late_entry_filter",
        "class": "MacdSignalTrendingUp4hStagedDeriskGivebackPartial67ChopTrendOnlyLateEntryFilterStrategy",
        "params": {
            "symbol": "BTC/USDT",
            "entry_timeframe": "4h",
            "trend_timeframe": "1d",
            "stop_atr_mult": 1.5,
            "require_signal_confirmation": True,
            "emit_once": True,
            "trend_spread_min": 0.005,
            "derisk_arm_r": 1.0,
            "derisk_giveback_r": 0.75,
            "derisk_close_pct": 0.67,
            "giveback_exit_arm_r": 1.5,
            "giveback_exit_floor_r": 0.25,
            "entry_ema_extension_atr_max": 1.25,
            "entry_bbw_ratio_min": 0.75,
        },
    },
    "macd_signal_btc_4h_trending_up_staged_derisk_giveback_partial67_chop_trend_tightened_late_entry_filter": {
        "enabled": False,
        "module": "trader.strategies.plugins.macd_signal_trending_up_4h_staged_derisk_giveback_partial67_chop_trend_tightened_late_entry_filter",
        "class": "MacdSignalTrendingUp4hStagedDeriskGivebackPartial67ChopTrendTightenedLateEntryFilterStrategy",
        "params": {
            "symbol": "BTC/USDT",
            "entry_timeframe": "4h",
            "trend_timeframe": "1d",
            "stop_atr_mult": 1.5,
            "require_signal_confirmation": True,
            "emit_once": True,
            "trend_spread_min": 0.005,
            "derisk_arm_r": 1.0,
            "derisk_giveback_r": 0.75,
            "derisk_close_pct": 0.67,
            "giveback_exit_arm_r": 1.5,
            "giveback_exit_floor_r": 0.25,
            "entry_ema_extension_atr_max": 1.25,
            "entry_bbw_ratio_min": 0.75,
            "chop_trend_extension_atr_trigger": 1.5,
        },
    },
    "macd_signal_btc_4h_trending_up_staged_derisk_giveback_partial67_transition_aware_late_entry_filter": {
        "enabled": False,
        "module": "trader.strategies.plugins.macd_signal_trending_up_4h_staged_derisk_giveback_partial67_transition_aware_late_entry_filter",
        "class": "MacdSignalTrendingUp4hStagedDeriskGivebackPartial67TransitionAwareLateEntryFilterStrategy",
        "params": {
            "symbol": "BTC/USDT",
            "entry_timeframe": "4h",
            "trend_timeframe": "1d",
            "stop_atr_mult": 1.5,
            "require_signal_confirmation": True,
            "emit_once": True,
            "trend_spread_min": 0.005,
            "derisk_arm_r": 1.0,
            "derisk_giveback_r": 0.75,
            "derisk_close_pct": 0.67,
            "giveback_exit_arm_r": 1.5,
            "giveback_exit_floor_r": 0.25,
            "entry_ema_extension_atr_max": 1.25,
            "transition_lookback_bars": 12,
            "transition_hist_ratio_max": 0.25,
            "transition_prior_positive_hist_min": 10.0,
        },
    },
    "macd_signal_btc_4h_trending_up_staged_derisk_giveback_partial67_transition_aware_tightened_late_entry_filter": {
        "enabled": True,
        "module": "trader.strategies.plugins.macd_signal_trending_up_4h_staged_derisk_giveback_partial67_transition_aware_tightened_late_entry_filter",
        "class": "MacdSignalTrendingUp4hStagedDeriskGivebackPartial67TransitionAwareTightenedLateEntryFilterStrategy",
        "params": {
            "symbol": "BTC/USDT",
            "entry_timeframe": "4h",
            "trend_timeframe": "1d",
            "stop_atr_mult": 1.5,
            "require_signal_confirmation": True,
            "emit_once": True,
            "trend_spread_min": 0.005,
            "derisk_arm_r": 1.0,
            "derisk_giveback_r": 0.75,
            "derisk_close_pct": 0.67,
            "giveback_exit_arm_r": 1.5,
            "giveback_exit_floor_r": 0.25,
            "entry_ema_extension_atr_max": 1.25,
            "transition_lookback_bars": 12,
            "transition_hist_ratio_max": 0.25,
            "transition_prior_positive_hist_min": 10.0,
            "transition_extension_atr_trigger": 3.0,
        },
    },
    "macd_signal_btc_4h_trending_down_staged_derisk_giveback_partial67_transition_aware_tightened_late_entry_filter": {
        "enabled": False,
        "module": "trader.strategies.plugins.macd_signal_trending_down_4h_staged_derisk_giveback_partial67_transition_aware_tightened_late_entry_filter",
        "class": "MacdSignalTrendingDown4hStagedDeriskGivebackPartial67TransitionAwareTightenedLateEntryFilterStrategy",
        "params": {
            "symbol": "BTC/USDT",
            "entry_timeframe": "4h",
            "trend_timeframe": "1d",
            "stop_atr_mult": 1.5,
            "require_signal_confirmation": True,
            "emit_once": True,
            "trend_spread_min": 0.005,
            "derisk_arm_r": 1.0,
            "derisk_giveback_r": 0.75,
            "derisk_close_pct": 0.67,
            "giveback_exit_arm_r": 1.5,
            "giveback_exit_floor_r": 0.25,
            "entry_ema_extension_atr_max": 1.25,
            "transition_lookback_bars": 12,
            "transition_hist_ratio_max": 0.25,
            "transition_prior_negative_hist_min": 10.0,
            "transition_extension_atr_trigger": 3.0,
        },
    },
    "macd_signal_btc_4h_trending_down_staged_derisk_giveback_partial67_snapback_guard": {
        "enabled": False,
        "module": "trader.strategies.plugins.macd_signal_trending_down_4h_staged_derisk_giveback_partial67_snapback_guard",
        "class": "MacdSignalTrendingDown4hStagedDeriskGivebackPartial67SnapbackGuardStrategy",
        "params": {
            "symbol": "BTC/USDT",
            "entry_timeframe": "4h",
            "trend_timeframe": "1d",
            "stop_atr_mult": 1.5,
            "require_signal_confirmation": True,
            "emit_once": True,
            "trend_spread_min": 0.005,
            "derisk_arm_r": 1.0,
            "derisk_giveback_r": 0.75,
            "derisk_close_pct": 0.67,
            "giveback_exit_arm_r": 1.5,
            "giveback_exit_floor_r": 0.25,
            "entry_ema_extension_atr_max": 1.25,
            "transition_lookback_bars": 12,
            "transition_hist_ratio_max": 0.25,
            "transition_prior_negative_hist_min": 10.0,
            "transition_extension_atr_trigger": 3.0,
            "snapback_guard_lookback_bars": 12,
            "snapback_downside_move_atr_min": 3.0,
            "snapback_entry_extension_atr_min": 1.25,
        },
    },
    "macd_signal_btc_4h_trending_down_staged_derisk_giveback_partial67_snapback_followthrough_guard": {
        "enabled": False,
        "module": "trader.strategies.plugins.macd_signal_trending_down_4h_staged_derisk_giveback_partial67_snapback_followthrough_guard",
        "class": "MacdSignalTrendingDown4hStagedDeriskGivebackPartial67SnapbackFollowthroughGuardStrategy",
        "params": {
            "symbol": "BTC/USDT",
            "entry_timeframe": "4h",
            "trend_timeframe": "1d",
            "stop_atr_mult": 1.5,
            "require_signal_confirmation": True,
            "emit_once": True,
            "trend_spread_min": 0.005,
            "derisk_arm_r": 1.0,
            "derisk_giveback_r": 0.75,
            "derisk_close_pct": 0.67,
            "giveback_exit_arm_r": 1.5,
            "giveback_exit_floor_r": 0.25,
            "entry_ema_extension_atr_max": 1.25,
            "transition_lookback_bars": 12,
            "transition_hist_ratio_max": 0.25,
            "transition_prior_negative_hist_min": 10.0,
            "transition_extension_atr_trigger": 3.0,
            "snapback_guard_lookback_bars": 12,
            "snapback_downside_move_atr_min": 3.0,
            "snapback_entry_extension_atr_min": 1.25,
            "followthrough_close_through_atr_min": 0.25,
            "followthrough_close_through_atr_max": 1.0,
            "followthrough_close_location_max": 0.35,
            "followthrough_downside_move_atr_max": 3.5,
            "followthrough_entry_extension_atr_max": 2.0,
            "followthrough_hist_expansion_min": 1.0,
            "followthrough_votes_min": 2,
        },
    },
    "macd_signal_btc_4h_trending_up_staged_derisk_giveback_partial67_squeeze_release_unconfirmed_late_entry_filter": {
        "enabled": False,
        "module": "trader.strategies.plugins.macd_signal_trending_up_4h_staged_derisk_giveback_partial67_squeeze_release_unconfirmed_late_entry_filter",
        "class": "MacdSignalTrendingUp4hStagedDeriskGivebackPartial67SqueezeReleaseUnconfirmedLateEntryFilterStrategy",
        "params": {
            "symbol": "BTC/USDT",
            "entry_timeframe": "4h",
            "trend_timeframe": "1d",
            "stop_atr_mult": 1.5,
            "require_signal_confirmation": True,
            "emit_once": True,
            "trend_spread_min": 0.005,
            "derisk_arm_r": 1.0,
            "derisk_giveback_r": 0.75,
            "derisk_close_pct": 0.67,
            "giveback_exit_arm_r": 1.5,
            "giveback_exit_floor_r": 0.25,
            "entry_ema_extension_atr_max": 1.25,
            "squeeze_pctrank_window": 100,
            "squeeze_trough_lookback": 20,
            "squeeze_release_current_pctrank_min": 60.0,
            "squeeze_trough_pctrank_max": 15.0,
            "weak_breakout_upper_fraction": 0.25,
        },
    },
    "macd_signal_btc_4h_trending_up_staged_derisk_giveback_partial67_chop_filter": {
        "enabled": False,
        "module": "trader.strategies.plugins.macd_signal_trending_up_4h_staged_derisk_giveback_partial67_chop_filter",
        "class": "MacdSignalTrendingUp4hStagedDeriskGivebackPartial67ChopFilterStrategy",
        "params": {
            "symbol": "BTC/USDT",
            "entry_timeframe": "4h",
            "trend_timeframe": "1d",
            "stop_atr_mult": 1.5,
            "require_signal_confirmation": True,
            "emit_once": True,
            "trend_spread_min": 0.005,
            "derisk_arm_r": 1.0,
            "derisk_giveback_r": 0.75,
            "derisk_close_pct": 0.67,
            "giveback_exit_arm_r": 1.5,
            "giveback_exit_floor_r": 0.25,
            "entry_adx_min": 22.0,
        },
    },
    "macd_signal_btc_4h_trending_up_staged_derisk_giveback_partial67_local_spread_filter": {
        "enabled": False,
        "module": "trader.strategies.plugins.macd_signal_trending_up_4h_staged_derisk_giveback_partial67_local_spread_filter",
        "class": "MacdSignalTrendingUp4hStagedDeriskGivebackPartial67LocalSpreadFilterStrategy",
        "params": {
            "symbol": "BTC/USDT",
            "entry_timeframe": "4h",
            "trend_timeframe": "1d",
            "stop_atr_mult": 1.5,
            "require_signal_confirmation": True,
            "emit_once": True,
            "trend_spread_min": 0.005,
            "derisk_arm_r": 1.0,
            "derisk_giveback_r": 0.75,
            "derisk_close_pct": 0.67,
            "giveback_exit_arm_r": 1.5,
            "giveback_exit_floor_r": 0.25,
            "entry_local_spread_min": 0.002,
        },
    },
    "macd_signal_btc_4h_trending_up_staged_derisk_giveback_partial67_chop_trend_filter": {
        "enabled": False,
        "module": "trader.strategies.plugins.macd_signal_trending_up_4h_staged_derisk_giveback_partial67_chop_trend_filter",
        "class": "MacdSignalTrendingUp4hStagedDeriskGivebackPartial67ChopTrendFilterStrategy",
        "params": {
            "symbol": "BTC/USDT",
            "entry_timeframe": "4h",
            "trend_timeframe": "1d",
            "stop_atr_mult": 1.5,
            "require_signal_confirmation": True,
            "emit_once": True,
            "trend_spread_min": 0.005,
            "derisk_arm_r": 1.0,
            "derisk_giveback_r": 0.75,
            "derisk_close_pct": 0.67,
            "giveback_exit_arm_r": 1.5,
            "giveback_exit_floor_r": 0.25,
            "entry_bbw_ratio_min": 0.75,
        },
    },
    "macd_signal_btc_4h_trending_up_staged_derisk_giveback_partial67_remainder_ratchet": {
        "enabled": False,
        "module": "trader.strategies.plugins.macd_signal_trending_up_4h_staged_derisk_giveback_partial67_remainder_ratchet",
        "class": "MacdSignalTrendingUp4hStagedDeriskGivebackPartial67RemainderRatchetStrategy",
        "params": {
            "symbol": "BTC/USDT",
            "entry_timeframe": "4h",
            "trend_timeframe": "1d",
            "stop_atr_mult": 1.5,
            "require_signal_confirmation": True,
            "emit_once": True,
            "trend_spread_min": 0.005,
            "derisk_arm_r": 1.0,
            "derisk_giveback_r": 0.75,
            "derisk_close_pct": 0.67,
            "giveback_exit_arm_r": 1.5,
            "giveback_exit_floor_r": 0.25,
            "remainder_ratchet_arm_r": 1.0,
            "remainder_ratchet_giveback_r": 1.0,
        },
    },
    "macd_signal_btc_4h_trending_up_staged_derisk_giveback_partial67_transition_buffer": {
        "enabled": False,
        "module": "trader.strategies.plugins.macd_signal_trending_up_4h_staged_derisk_giveback_partial67_transition_buffer",
        "class": "MacdSignalTrendingUp4hStagedDeriskGivebackPartial67TransitionBufferStrategy",
        "params": {
            "symbol": "BTC/USDT",
            "entry_timeframe": "4h",
            "trend_timeframe": "1d",
            "stop_atr_mult": 1.5,
            "require_signal_confirmation": True,
            "emit_once": True,
            "trend_spread_min": 0.005,
            "derisk_arm_r": 1.0,
            "derisk_giveback_r": 0.75,
            "derisk_close_pct": 0.67,
            "giveback_exit_arm_r": 1.5,
            "giveback_exit_floor_r": 0.25,
            "trend_persistence_bars": 3,
        },
    },
    "macd_signal_btc_4h_trending_up_staged_derisk_giveback_partial67_transition_decay_filter": {
        "enabled": False,
        "module": "trader.strategies.plugins.macd_signal_trending_up_4h_staged_derisk_giveback_partial67_transition_decay_filter",
        "class": "MacdSignalTrendingUp4hStagedDeriskGivebackPartial67TransitionDecayFilterStrategy",
        "params": {
            "symbol": "BTC/USDT",
            "entry_timeframe": "4h",
            "trend_timeframe": "1d",
            "stop_atr_mult": 1.5,
            "require_signal_confirmation": True,
            "emit_once": True,
            "trend_spread_min": 0.005,
            "derisk_arm_r": 1.0,
            "derisk_giveback_r": 0.75,
            "derisk_close_pct": 0.67,
            "giveback_exit_arm_r": 1.5,
            "giveback_exit_floor_r": 0.25,
            "trend_spread_slope_bars": 3,
            "trend_spread_slope_min": 0.0,
        },
    },
    "ema_cross_7_19_long_only": {
        "enabled": False,
        "module": "trader.strategies.plugins.ema_cross_7_19",
        "class": "EmaCross719LongOnlyStrategy",
        "params": {"timeframe": "4h", "atr_mult": 1.5},
    },
    "bb_fade_squeeze_1h": {
        "enabled": False,
        "module": "trader.strategies.plugins.bb_fade_squeeze_1h",
        "class": "BbFadeSqueeze1hStrategy",
        "params": {
            "timeframe": "1h",
            "htf_timeframe": "4h",
            "rsi_entry": 30.0,
            "rsi_exit": 55.0,
            "bbw_pctrank_max": 20.0,
            "bbw_pctrank_window": 100,
            "htf_adx_max": 20.0,
            "htf_adx_exit": 25.0,
            "stop_atr_mult": 1.5,
            "cooldown_bars": 5,
            "emit_once": True,
        },
    },
    "rsi2_pullback_1h": {
        "enabled": False,
        "module": "trader.strategies.plugins.rsi2_pullback_1h",
        "class": "Rsi2Pullback1hStrategy",
        "params": {
            "timeframe": "1h",
            "htf_timeframe": "4h",
            "rsi_period": 2,
            "rsi_entry": 10.0,
            "rsi_exit": 70.0,
            "sma_trend_len": 200,
            "sma_exit_len": 5,
            "htf_sma_trend_len": 200,
            "stop_atr_mult": 2.0,
            "max_hold_bars": 10,
            "cooldown_bars": 4,
            "emit_once": True,
        },
    },
    "rsi2_pullback_1h_sma5_gap_guard": {
        "enabled": False,
        "module": "trader.strategies.plugins.rsi2_pullback_1h_sma5_gap_guard",
        "class": "Rsi2Pullback1hSma5GapGuardStrategy",
        "params": {
            "timeframe": "1h",
            "htf_timeframe": "4h",
            "rsi_period": 2,
            "rsi_entry": 10.0,
            "rsi_exit": 70.0,
            "sma_trend_len": 200,
            "sma_exit_len": 5,
            "htf_sma_trend_len": 200,
            "stop_atr_mult": 2.0,
            "max_hold_bars": 10,
            "cooldown_bars": 4,
            "emit_once": True,
            "min_sma5_gap_atr": 0.75,
        },
    },
    "donchian_range_fade_4h": {
        "enabled": False,
        "module": "trader.strategies.plugins.donchian_range_fade_4h",
        "class": "DonchianRangeFade4hStrategy",
        "params": {
            "timeframe": "4h",
            "donchian_len": 20,
            "range_window": 15,
            "range_width_cv_max": 0.10,
            "touch_atr_band": 0.25,
            "min_lower_touches": 1,
            "min_upper_touches": 1,
            "rsi_entry": 40.0,
            "exit_target": "mid",
            "break_atr_mult": 0.5,
            "stop_atr_mult": 1.5,
            "cooldown_bars": 3,
            "emit_once": True,
        },
    },
    "donchian_range_fade_4h_range_width_cv_013": {
        "enabled": True,
        "module": "trader.strategies.plugins.donchian_range_fade_4h_range_width_cv_013",
        "class": "DonchianRangeFade4hRangeWidthCv013Strategy",
        "params": {
            "timeframe": "4h",
            "donchian_len": 20,
            "range_window": 15,
            "range_width_cv_max": 0.13,
            "touch_atr_band": 0.25,
            "min_lower_touches": 1,
            "min_upper_touches": 1,
            "rsi_entry": 40.0,
            "exit_target": "mid",
            "break_atr_mult": 0.5,
            "stop_atr_mult": 1.5,
            "cooldown_bars": 3,
            "emit_once": True,
        },
    },
    "donchian_range_fade_4h_range_width_cv_013_short": {
        "enabled": False,
        "module": "trader.strategies.plugins.donchian_range_fade_4h_range_width_cv_013_short",
        "class": "DonchianRangeFade4hRangeWidthCv013ShortStrategy",
        "params": {
            "timeframe": "4h",
            "donchian_len": 20,
            "range_window": 15,
            "range_width_cv_max": 0.13,
            "touch_atr_band": 0.25,
            "min_lower_touches": 1,
            "min_upper_touches": 1,
            "rsi_entry": 60.0,
            "exit_target": "mid",
            "break_atr_mult": 0.5,
            "stop_atr_mult": 1.5,
            "cooldown_bars": 3,
            "emit_once": True,
        },
    },
    "donchian_range_fade_4h_range_width_cv_013_mid_drift_guard": {
        "enabled": False,
        "module": "trader.strategies.plugins.donchian_range_fade_4h_range_width_cv_013_mid_drift_guard",
        "class": "DonchianRangeFade4hRangeWidthCv013MidDriftGuardStrategy",
        "params": {
            "timeframe": "4h",
            "donchian_len": 20,
            "range_window": 15,
            "range_width_cv_max": 0.13,
            "mid_drift_ratio_max": 0.10,
            "touch_atr_band": 0.25,
            "min_lower_touches": 1,
            "min_upper_touches": 1,
            "rsi_entry": 40.0,
            "exit_target": "mid",
            "break_atr_mult": 0.5,
            "stop_atr_mult": 1.5,
            "cooldown_bars": 3,
            "emit_once": True,
        },
    },
    "donchian_range_fade_4h_range_width_cv_013_touch_imbalance_guard": {
        "enabled": False,
        "module": "trader.strategies.plugins.donchian_range_fade_4h_range_width_cv_013_touch_imbalance_guard",
        "class": "DonchianRangeFade4hRangeWidthCv013TouchImbalanceGuardStrategy",
        "params": {
            "timeframe": "4h",
            "donchian_len": 20,
            "range_window": 15,
            "range_width_cv_max": 0.13,
            "touch_imbalance_ratio_max": 2.5,
            "touch_atr_band": 0.25,
            "min_lower_touches": 1,
            "min_upper_touches": 1,
            "rsi_entry": 40.0,
            "exit_target": "mid",
            "break_atr_mult": 0.5,
            "stop_atr_mult": 1.5,
            "cooldown_bars": 3,
            "emit_once": True,
        },
    },
    "rsi_mean_reversion_15m": {
        "enabled": False,
        "module": "trader.strategies.plugins.rsi_mean_reversion",
        "class": "RsiMeanReversionStrategy",
        "params": {
            "timeframe": "15m",
            "rsi_entry": 25.0,
            "rsi_exit": 60.0,
            "adx_max": 25.0,
            "adx_exit": 30.0,
            "stop_atr_mult": 1.5,
            "cooldown_bars": 5,
        },
    },
    "rsi_mean_reversion_1h": {
        "enabled": False,
        "module": "trader.strategies.plugins.rsi_mean_reversion_1h",
        "class": "RsiMeanReversion1hStrategy",
        "params": {
            "timeframe": "1h",
            "rsi_entry": 25.0,
            "rsi_exit": 60.0,
            "adx_max": 25.0,
            "adx_exit": 30.0,
            "stop_atr_mult": 1.5,
            "cooldown_bars": 5,
        },
    },
}


STRATEGY_CATALOG_CLASSIFICATION: dict[str, str] = {
    "fixture_long": CATALOG_CLASS_FIXTURE,
    "fixture_exit": CATALOG_CLASS_FIXTURE,
    "macd_zero_line_btc_1d": CATALOG_CLASS_SUPERSEDED_RESEARCH,
    "macd_zero_line_btc_1d_trending_up": CATALOG_CLASS_SUPERSEDED_RESEARCH,
    "macd_signal_btc_4h_trending_up": CATALOG_CLASS_SUPERSEDED_RESEARCH,
    "macd_signal_btc_4h_trending_up_confirmed": CATALOG_CLASS_SUPERSEDED_RESEARCH,
    "macd_signal_btc_4h_trending_up_confirmed_failfast": CATALOG_CLASS_SUPERSEDED_RESEARCH,
    "macd_signal_btc_4h_trending_up_underwater_ema_exit": CATALOG_CLASS_SUPERSEDED_RESEARCH,
    "macd_signal_btc_4h_trending_up_staged_derisk_giveback": CATALOG_CLASS_SUPERSEDED_RESEARCH,
    "macd_signal_btc_4h_trending_up_staged_derisk_giveback_partial67": CATALOG_CLASS_SUPERSEDED_RESEARCH,
    "macd_signal_btc_4h_trending_up_staged_derisk_giveback_partial67_late_entry_filter": CATALOG_CLASS_SUPERSEDED_RESEARCH,
    "macd_signal_btc_4h_trending_up_staged_derisk_giveback_partial67_context_gated_late_entry_filter": CATALOG_CLASS_SUPERSEDED_RESEARCH,
    "macd_signal_btc_4h_trending_up_staged_derisk_giveback_partial67_trend_decay_only_late_entry_filter": CATALOG_CLASS_SUPERSEDED_RESEARCH,
    "macd_signal_btc_4h_trending_up_staged_derisk_giveback_partial67_chop_trend_only_late_entry_filter": CATALOG_CLASS_SUPERSEDED_RESEARCH,
    "macd_signal_btc_4h_trending_up_staged_derisk_giveback_partial67_chop_trend_tightened_late_entry_filter": CATALOG_CLASS_SUPERSEDED_RESEARCH,
    "macd_signal_btc_4h_trending_up_staged_derisk_giveback_partial67_transition_aware_late_entry_filter": CATALOG_CLASS_SUPERSEDED_RESEARCH,
    "macd_signal_btc_4h_trending_up_staged_derisk_giveback_partial67_transition_aware_tightened_late_entry_filter": CATALOG_CLASS_RUNTIME,
    "macd_signal_btc_4h_trending_down_staged_derisk_giveback_partial67_transition_aware_tightened_late_entry_filter": CATALOG_CLASS_RETIRE_CANDIDATE,
    "macd_signal_btc_4h_trending_down_staged_derisk_giveback_partial67_snapback_guard": CATALOG_CLASS_RETIRE_CANDIDATE,
    "macd_signal_btc_4h_trending_down_staged_derisk_giveback_partial67_snapback_followthrough_guard": CATALOG_CLASS_RETIRE_CANDIDATE,
    "macd_signal_btc_4h_trending_up_staged_derisk_giveback_partial67_squeeze_release_unconfirmed_late_entry_filter": CATALOG_CLASS_SUPERSEDED_RESEARCH,
    "macd_signal_btc_4h_trending_up_staged_derisk_giveback_partial67_chop_filter": CATALOG_CLASS_SUPERSEDED_RESEARCH,
    "macd_signal_btc_4h_trending_up_staged_derisk_giveback_partial67_local_spread_filter": CATALOG_CLASS_SUPERSEDED_RESEARCH,
    "macd_signal_btc_4h_trending_up_staged_derisk_giveback_partial67_chop_trend_filter": CATALOG_CLASS_SUPERSEDED_RESEARCH,
    "macd_signal_btc_4h_trending_up_staged_derisk_giveback_partial67_remainder_ratchet": CATALOG_CLASS_SUPERSEDED_RESEARCH,
    "macd_signal_btc_4h_trending_up_staged_derisk_giveback_partial67_transition_buffer": CATALOG_CLASS_SUPERSEDED_RESEARCH,
    "macd_signal_btc_4h_trending_up_staged_derisk_giveback_partial67_transition_decay_filter": CATALOG_CLASS_SUPERSEDED_RESEARCH,
    "ema_cross_7_19_long_only": CATALOG_CLASS_FIXTURE,
    "bb_fade_squeeze_1h": CATALOG_CLASS_ACTIVE_RESEARCH,
    "rsi2_pullback_1h": CATALOG_CLASS_SUPERSEDED_RESEARCH,
    "rsi2_pullback_1h_sma5_gap_guard": CATALOG_CLASS_ACTIVE_RESEARCH,
    "donchian_range_fade_4h": CATALOG_CLASS_SUPERSEDED_RESEARCH,
    "donchian_range_fade_4h_range_width_cv_013": CATALOG_CLASS_RUNTIME,
    "donchian_range_fade_4h_range_width_cv_013_short": CATALOG_CLASS_RUNTIME,
    "donchian_range_fade_4h_range_width_cv_013_mid_drift_guard": CATALOG_CLASS_RETIRE_CANDIDATE,
    "donchian_range_fade_4h_range_width_cv_013_touch_imbalance_guard": CATALOG_CLASS_RETIRE_CANDIDATE,
    "rsi_mean_reversion_15m": CATALOG_CLASS_SUPERSEDED_RESEARCH,
    "rsi_mean_reversion_1h": CATALOG_CLASS_ACTIVE_RESEARCH,
}


STRATEGY_CATALOG_CLASSIFICATION_NOTES: dict[str, str] = {
    "fixture_long": "Tooling fixture for plugin registry checks.",
    "fixture_exit": "Tooling fixture for plugin exit-intent checks.",
    "ema_cross_7_19_long_only": "Research fixture/checklist gate; not on a promotion track.",
    "bb_fade_squeeze_1h": "Parked RANGING research candidate; not promoted.",
    "rsi2_pullback_1h_sma5_gap_guard": "Current RSI2 pullback research branch.",
    "rsi_mean_reversion_1h": "Current RSI mean-reversion research branch.",
    "macd_signal_btc_4h_trending_down_staged_derisk_giveback_partial67_transition_aware_tightened_late_entry_filter": "Slot A SHORT freeze read says do not promote.",
    "macd_signal_btc_4h_trending_down_staged_derisk_giveback_partial67_snapback_guard": "Slot A SHORT snapback guard branch is frozen.",
    "macd_signal_btc_4h_trending_down_staged_derisk_giveback_partial67_snapback_followthrough_guard": "Slot A SHORT snapback follow-through branch is frozen.",
    "donchian_range_fade_4h_range_width_cv_013_mid_drift_guard": "Guard experiment did not improve the promoted Donchian runtime branch.",
    "donchian_range_fade_4h_range_width_cv_013_touch_imbalance_guard": "Guard experiment did not improve the promoted Donchian runtime branch.",
}


def _validate_catalog_classification() -> None:
    catalog_ids = set(STRATEGY_CATALOG)
    classified_ids = set(STRATEGY_CATALOG_CLASSIFICATION)
    note_ids = set(STRATEGY_CATALOG_CLASSIFICATION_NOTES)
    missing_ids = sorted(catalog_ids - classified_ids)
    extra_ids = sorted(classified_ids - catalog_ids)
    extra_note_ids = sorted(note_ids - catalog_ids)
    invalid = sorted(
        strategy_id
        for strategy_id, classification in STRATEGY_CATALOG_CLASSIFICATION.items()
        if classification not in VALID_CATALOG_CLASSIFICATIONS
    )
    if missing_ids or extra_ids or extra_note_ids or invalid:
        problems = []
        if missing_ids:
            problems.append(f"missing classifications: {missing_ids}")
        if extra_ids:
            problems.append(f"unknown classification ids: {extra_ids}")
        if extra_note_ids:
            problems.append(f"unknown classification note ids: {extra_note_ids}")
        if invalid:
            problems.append(f"invalid classifications: {invalid}")
        raise ValueError("; ".join(problems))


def get_strategy_classification(strategy_id: str) -> str | None:
    """Return the research/runtime classification for a catalog strategy id."""
    return STRATEGY_CATALOG_CLASSIFICATION.get(str(strategy_id))


def get_strategy_classification_note(strategy_id: str) -> str | None:
    """Return the classification note for a catalog strategy id, when present."""
    return STRATEGY_CATALOG_CLASSIFICATION_NOTES.get(str(strategy_id))


def get_strategy_catalog(enabled: Iterable[str] | None = None) -> dict[str, dict[str, Any]]:
    """Return a per-call catalog copy with selected plugin ids enabled."""
    catalog = copy.deepcopy(STRATEGY_CATALOG)
    for strategy_id in enabled or []:
        entry = catalog.get(str(strategy_id))
        if entry is not None:
            entry["enabled"] = True
    return catalog


_validate_catalog_classification()
